export default {
  "settingsButton": "Settings",
  "openHistory": "Open history",
  "title": "CONSOLE SETTINGS",
  "language": "Language",
  "server": "Signal K server",
  "serverLabel": "Signal K server address",
  "serverHint": "Server IP or hostname and port. Example: 192.168.1.10:3000",
  "savedAddress": "Address saved.",
  "saveError": "Could not save. Please try again.",
  "invalidAddress": "Invalid address. Example: http://192.168.1.10:3000",
  "saving": "SAVING…",
  "connect": "SAVE AND CONNECT",
  "depthEnabled": "Enable depth alarm",
  "minWind": "Minimum upwind angle",
  "maxWind": "Maximum upwind angle",
  "rudder": "Rudder alert",
  "depth": "Depth alarm",
  "sound": "Depth alarm sound",
  "soundHint": "Repeats while depth is below the limit. On the web, tap the screen to enable audio.",
  "testSound": "TEST SOUND",
  "intensity": "Night mode intensity",
  "intensityHint": "Applies when night mode is enabled. A lower percentage makes the screen darker.",
  "night": "Night mode",
  "close": "CLOSE",
  "historySaved": "Duration saved and applied.",
  "saveHours": "SAVE HOURS",
  "historyTitle": "{metric} history hours",
  "historyLabel": "{metric} history hours to retain",
  "historyHint": "From 1 to {max} hours. Default: 2. Reducing this removes older samples.",
  "historyInvalid": "Enter a whole number between 1 and {max}.",
  "connected": "CONNECTED",
  "disconnected": "NOT CONNECTED",
  "openSettings": "Open settings",
  "aisData": "AIS DATA",
  "showAis": "Show AIS data",
  "hideAis": "Hide AIS data",
  "vessel": "AIS VESSEL",
  "distance": "DISTANCE",
  "speed": "SPEED",
  "course": "COURSE (COG)",
  "closeAis": "Close AIS information",
  "aisTarget": "{name}, {distance} nautical miles",
  "heelLabel": "HEEL",
  "rudderLabel": "RUDDER",
  "port": "PORT",
  "starboard": "STBD",
  "centered": "CENTERED",
  "noData": "NO DATA",
  "sail": "SAIL",
  "engine": "ENGINE",
  "active": "active",
  "inactive": "inactive",
  "modeState": "{mode}: {state}",
  "depthLabel": "DEPTH",
  "pilotLabel": "PILOT",
  "pilotAuto": "AUTO",
  "pilotWind": "WIND",
  "pilotTrack": "TRACK",
  "pilotStandby": "STBY",
  "maximum": "MAX",
  "minimum": "MIN",
  "historyHeading": "{metric} · HISTORY",
  "historyWaiting": "Waiting for more readings to draw the chart.",
  "historyDescription": "{metric} history, {count} readings, scale up to {range} {unit}",
  "muted": "Alarm muted",
  "muteMinute": "Mute alarm for one minute",
  "alert": "alert",
  "rudderDescription": "Rudder {value}, {state}",
  "heelDescription": "Heel {angle} degrees, {side}. Rudder {rudder}",
  "headingDescription": "Heading {angle} degrees, {cardinal}",
  "headingNoData": "No heading data",
  "windShift": "WIND SHIFT",
  "west": "W",
  "portInitial": "P",
  "starboardInitial": "S",
  "trueWindInitial": "T",
  "startupError": "Console startup error",
  "errorComponents": "Affected components",
  "diagnostics": "Collecting diagnostics…",
  "historyGesture": "Double-tap to open history. Hold for 3 seconds to reset.",
  "resetGesture": "Hold for 3 seconds to reset the maximum and history."
};
