export default {
  "settingsButton": "Ajustes",
  "openHistory": "Abrir historial",
  "title": "AJUSTES DE CONSOLA",
  "language": "Idioma",
  "server": "Servidor Signal K",
  "serverLabel": "Dirección del servidor Signal K",
  "serverHint": "IP o nombre del servidor y puerto. Ejemplo: 192.168.1.10:3000",
  "savedAddress": "Dirección guardada.",
  "saveError": "No se pudo guardar. Inténtalo de nuevo.",
  "invalidAddress": "Dirección no válida. Ejemplo: http://192.168.1.10:3000",
  "saving": "GUARDANDO…",
  "connect": "GUARDAR Y CONECTAR",
  "depthEnabled": "Activar alarma de profundidad",
  "minWind": "Mínimo Ceñida",
  "maxWind": "Máximo Ceñida",
  "rudder": "Alerta de Timón",
  "depth": "Alarma de profundidad",
  "sound": "Sonido de alarma de profundidad",
  "soundHint": "Aviso repetido mientras la profundidad esté por debajo del límite. En web, toca la pantalla para habilitar el audio.",
  "testSound": "PROBAR SONIDO",
  "intensity": "Intensidad del modo noche",
  "intensityHint": "Se aplica al activar el modo noche. Un porcentaje menor oscurece más la pantalla.",
  "night": "Modo Noche",
  "close": "CERRAR",
  "historySaved": "Duración guardada y aplicada.",
  "saveHours": "GUARDAR HORAS",
  "historyTitle": "Horas de historial {metric}",
  "historyLabel": "Horas de historial {metric} a conservar",
  "historyHint": "De 1 a {max} horas. Por defecto: 2. Al reducirlas se eliminan las muestras más antiguas.",
  "historyInvalid": "Introduce un número entero entre 1 y {max}.",
  "connected": "CONECTADO",
  "disconnected": "SIN CONEXIÓN",
  "openSettings": "Abrir ajustes",
  "aisData": "DATOS AIS",
  "showAis": "Mostrar datos AIS",
  "hideAis": "Ocultar datos AIS",
  "vessel": "BARCO AIS",
  "distance": "DISTANCIA",
  "speed": "VELOCIDAD",
  "course": "RUMBO (COG)",
  "closeAis": "Cerrar información AIS",
  "aisTarget": "{name}, {distance} millas náuticas",
  "heelLabel": "ESCORA",
  "rudderLabel": "TIMÓN",
  "port": "BABOR",
  "starboard": "ESTRIBOR",
  "centered": "CENTRADO",
  "noData": "SIN DATOS",
  "sail": "VELA",
  "engine": "MOTOR",
  "active": "activo",
  "inactive": "inactivo",
  "modeState": "{mode}: {state}",
  "depthLabel": "SONDA",
  "pilotLabel": "PILOTO",
  "pilotAuto": "AUTO",
  "pilotWind": "VIENTO",
  "pilotTrack": "RUTA",
  "pilotStandby": "ESPERA",
  "maximum": "MÁX",
  "minimum": "MÍN",
  "historyHeading": "{metric} · HISTORIAL",
  "historyWaiting": "Esperando más lecturas para dibujar el gráfico.",
  "historyDescription": "Historial de {metric}, {count} valores, escala hasta {range} {unit}",
  "muted": "Alarma silenciada",
  "muteMinute": "Silenciar alarma un minuto",
  "alert": "alerta",
  "rudderDescription": "Timón {value}, {state}",
  "heelDescription": "Escora {angle} grados, {side}. Timón {rudder}",
  "headingDescription": "Rumbo {angle} grados, {cardinal}",
  "headingNoData": "Rumbo sin datos",
  "windShift": "ROLADA",
  "west": "O",
  "portInitial": "B",
  "starboardInitial": "E",
  "trueWindInitial": "R",
  "startupError": "Error al iniciar la consola",
  "errorComponents": "Componentes implicados",
  "diagnostics": "Recopilando diagnóstico…",
  "historyGesture": "Dos toques rápidos abren el historial. Mantén pulsado 3 segundos para reiniciar.",
  "resetGesture": "Mantén pulsado durante 3 segundos para reiniciar el máximo y el historial."
};
