export default {
  "settingsButton": "Réglages",
  "openHistory": "Ouvrir l’historique",
  "title": "RÉGLAGES DE LA CONSOLE",
  "language": "Langue",
  "server": "Serveur Signal K",
  "serverLabel": "Adresse du serveur Signal K",
  "serverHint": "Adresse IP ou nom du serveur et port. Exemple : 192.168.1.10:3000",
  "savedAddress": "Adresse enregistrée.",
  "saveError": "Impossible d’enregistrer. Réessayez.",
  "invalidAddress": "Adresse invalide. Exemple : http://192.168.1.10:3000",
  "saving": "ENREGISTREMENT…",
  "connect": "ENREGISTRER ET CONNECTER",
  "depthEnabled": "Activer l’alarme de profondeur",
  "minWind": "Angle minimum au près",
  "maxWind": "Angle maximum au près",
  "rudder": "Alerte de barre",
  "depth": "Alarme de profondeur",
  "sound": "Son de l’alarme de profondeur",
  "soundHint": "Se répète tant que la profondeur est inférieure au seuil. Sur le Web, touchez l’écran pour activer le son.",
  "testSound": "TESTER LE SON",
  "intensity": "Intensité du mode nuit",
  "intensityHint": "S’applique à l’activation du mode nuit. Un pourcentage plus faible assombrit davantage l’écran.",
  "night": "Mode nuit",
  "close": "FERMER",
  "historySaved": "Durée enregistrée et appliquée.",
  "saveHours": "ENREGISTRER LA DURÉE",
  "historyTitle": "Durée de l’historique {metric}",
  "historyLabel": "Nombre d’heures d’historique {metric} à conserver",
  "historyHint": "De 1 à {max} heures. Par défaut : 2. Réduire cette durée supprime les mesures les plus anciennes.",
  "historyInvalid": "Saisissez un nombre entier entre 1 et {max}.",
  "connected": "CONNECTÉ",
  "disconnected": "DÉCONNECTÉ",
  "openSettings": "Ouvrir les réglages",
  "aisData": "DONNÉES AIS",
  "showAis": "Afficher les données AIS",
  "hideAis": "Masquer les données AIS",
  "vessel": "NAVIRE AIS",
  "distance": "DISTANCE",
  "speed": "VITESSE",
  "course": "ROUTE (COG)",
  "closeAis": "Fermer les informations AIS",
  "aisTarget": "{name}, {distance} milles nautiques",
  "heelLabel": "GÎTE",
  "rudderLabel": "BARRE",
  "port": "BÂBORD",
  "starboard": "TRIBORD",
  "centered": "CENTRÉ",
  "noData": "SANS DONNÉES",
  "sail": "VOILE",
  "engine": "MOTEUR",
  "active": "actif",
  "inactive": "inactif",
  "modeState": "{mode} : {state}",
  "depthLabel": "SONDE",
  "pilotLabel": "PILOTE",
  "pilotAuto": "AUTO",
  "pilotWind": "VENT",
  "pilotTrack": "ROUTE",
  "pilotStandby": "VEILLE",
  "maximum": "MAX",
  "minimum": "MIN",
  "historyHeading": "{metric} · HISTORIQUE",
  "historyWaiting": "En attente de mesures supplémentaires pour tracer le graphique.",
  "historyDescription": "Historique {metric}, {count} mesures, échelle jusqu’à {range} {unit}",
  "muted": "Alarme silencieuse",
  "muteMinute": "Couper le son de l’alarme pendant une minute",
  "alert": "alerte",
  "rudderDescription": "Barre {value}, {state}",
  "heelDescription": "Gîte de {angle} degrés, {side}. Barre {rudder}",
  "headingDescription": "Cap {angle} degrés, {cardinal}",
  "headingNoData": "Cap indisponible",
  "windShift": "SAUTE DE VENT",
  "west": "O",
  "portInitial": "B",
  "starboardInitial": "T",
  "trueWindInitial": "V",
  "startupError": "Erreur au démarrage de la console",
  "errorComponents": "Composants concernés",
  "diagnostics": "Collecte du diagnostic…",
  "historyGesture": "Touchez deux fois pour ouvrir l’historique. Maintenez pendant 3 secondes pour réinitialiser.",
  "resetGesture": "Maintenez pendant 3 secondes pour réinitialiser le maximum et l’historique."
};
